#!/usr/bin/env python3
"""Builds the V5 central ingredient dictionary from the bundled catalog.

Outputs (all generated, do not edit by hand):
  MealRoutine/Recipes/ingredients.v2.json   bundled copy for offline / personal pantry
  server/db/ingredients.v2.json             same file, read by the in-memory store and tests

Shape (V5.1): every entry has a language-independent `id`, locale-keyed display `names`
(`{"tr-TR": "Domates"}`) and locale-keyed `aliases` (`{"tr-TR": ["İri domates"]}`). Only
tr-TR data exists today; another locale is added as data, not code.

`0012_pantry.sql` is frozen. Its seed block is checked against the tr-TR rows here; when the
dictionary changes, the script stops and the new rows belong in a new migration.

Every merge below is an explicit dictionary decision. Display-name similarity never merges
two catalog ids on its own: `pepper` (Karabiber) and `peppers` (yeşil biber) stay apart.
A name or synonym that would point at two entries is dropped from the resolution keys.

Run: python3 Tools/build_ingredient_dictionary.py
"""
from __future__ import annotations

import collections
import json
import re
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "MealRoutine/Recipes/recipes.v1.json"
ALIASES = ROOT / "MealRoutine/Recipes/ingredient-aliases.tr.json"
OUT_APP = ROOT / "MealRoutine/Recipes/ingredients.v2.json"
OUT_SERVER = ROOT / "server/db/ingredients.v2.json"
SOURCE_LOCALE = "tr-TR"
MIGRATION = ROOT / "server/db/migrations/0012_pantry.sql"
BEGIN = "-- BEGIN INGREDIENT SEED (generated by Tools/build_ingredient_dictionary.py)"
END = "-- END INGREDIENT SEED"

# Catalog id -> canonical dictionary id. Same ingredient written two ways in the catalog.
MERGES = {
    "tomatoes": "tomato",
    "eggs": "egg",
    "onions": "onion",
    "potatoes": "potato",
    "shallots": "shallot",
    "cucumbers": "cucumber",
    "chillies": "chilli",
    "chili": "chilli",
    "driedchili": "driedchilli",
    "greenchili": "greenchilli",
    "pepper": "blackpepper",
    "yoghurt": "yogurt",
    "scallion": "springonion",
    "spring": "springonion",
    "biber": "peppers",
    "kecap": "kecapmanis",
}

# Turkish display names that would otherwise collide with a different ingredient.
NAME_OVERRIDES = {
    "oregano": "Kekik (oregano)",
    "cornflour": "Mısır nişastası",
    "pita": "Pita ekmeği",
    "chillipowder": "Toz acı biber",
    "kashmirichili": "Kashmiri acı biber tozu",
}

# Pantry staples users add at home that the catalog does not use yet.
EXTRAS = [
    {"id": "cherry-tomato", "name": "Cherry domates", "synonyms": [], "sourceIds": []},
    {"id": "pasta", "name": "Makarna", "synonyms": [], "sourceIds": []},
]


def fold(raw: str) -> str:
    text = raw.strip().replace("İ", "i").lower()
    text = unicodedata.normalize("NFD", text)
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    text = text.replace("ı", "i")
    return "".join(ch for ch in text if ch.isascii() and ch.isalnum())


def build() -> list[dict]:
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    aliases = json.loads(ALIASES.read_text(encoding="utf-8"))["aliases"]
    names: dict[str, collections.Counter] = collections.defaultdict(collections.Counter)
    for recipe in catalog["recipes"]:
        for line in recipe["ingredients"]:
            name = (line["name"].get("tr") or line["name"].get("en") or "").strip()
            if name:
                names[line["id"]][name] += 1
    for source, target in MERGES.items():
        if source not in names or target not in names:
            sys.exit(f"merge {source}->{target} refers to an id missing from the catalog")

    entries: dict[str, dict] = {}
    for cid in sorted(names):
        canonical = MERGES.get(cid, cid)
        entry = entries.setdefault(canonical, {"id": canonical, "name": "", "synonyms": set(), "sourceIds": set()})
        if cid != canonical:
            entry["sourceIds"].add(cid)
        entry["synonyms"].update(names[cid])
    for cid, entry in entries.items():
        entry["name"] = NAME_OVERRIDES.get(cid) or aliases.get(cid) or names[cid].most_common(1)[0][0]
    for extra in EXTRAS:
        if extra["id"] in entries:
            sys.exit(f"extra {extra['id']} already exists in the catalog")
        entries[extra["id"]] = {**extra, "synonyms": set(extra["synonyms"]), "sourceIds": set(extra["sourceIds"])}

    by_name = collections.Counter(fold(entry["name"]) for entry in entries.values())
    duplicates = sorted(key for key, count in by_name.items() if count > 1)
    if duplicates:
        sys.exit(f"display names collide: {duplicates}")

    owners: dict[str, set[str]] = collections.defaultdict(set)
    for entry in entries.values():
        owners[fold(entry["name"])].add(entry["id"])
        for synonym in entry["synonyms"]:
            owners[fold(synonym)].add(entry["id"])

    result = []
    for cid in sorted(entries):
        entry = entries[cid]
        own = fold(entry["name"])
        synonyms = sorted(
            {s for s in entry["synonyms"] if fold(s) and fold(s) != own and len(owners[fold(s)]) == 1},
            key=lambda s: (fold(s), s),
        )
        result.append({
            "id": cid,
            "name": entry["name"],
            "synonyms": synonyms,
            "sourceIds": sorted(entry["sourceIds"]),
        })
    return result


def sql_text(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def sql_array(values: list[str]) -> str:
    if not values:
        return "'{}'::text[]"
    return "ARRAY[" + ", ".join(sql_text(v) for v in values) + "]::text[]"


def seed_sql(entries: list[dict]) -> str:
    rows = [
        f"  ({sql_text(e['id'])}, {sql_text(e['name'])}, {sql_array(e['synonyms'])}, {sql_array(e['sourceIds'])})"
        for e in entries
    ]
    return (
        f"{BEGIN}\n"
        "INSERT INTO ingredients (id, display_name, synonyms, source_ids) VALUES\n"
        + ",\n".join(rows)
        + "\nON CONFLICT (id) DO NOTHING;\n"
        f"{END}"
    )


def localized(entry: dict) -> dict:
    return {
        "id": entry["id"],
        "names": {SOURCE_LOCALE: entry["name"]},
        "aliases": {SOURCE_LOCALE: entry["synonyms"]},
        "sourceIds": entry["sourceIds"],
    }


def main() -> None:
    entries = build()
    migration = MIGRATION.read_text(encoding="utf-8")
    match = re.search(re.escape(BEGIN) + r".*?" + re.escape(END), migration, re.S)
    if not match:
        sys.exit("0012_pantry.sql has no INGREDIENT SEED markers")
    if match.group(0) != seed_sql(entries):
        sys.exit("dictionary differs from the frozen 0012 seed; add the change in a new migration")
    document = {
        "version": 2,
        "sourceLocale": SOURCE_LOCALE,
        "locales": [SOURCE_LOCALE],
        "ingredients": [localized(entry) for entry in entries],
    }
    text = json.dumps(document, ensure_ascii=False, indent=2) + "\n"
    OUT_APP.write_text(text, encoding="utf-8")
    OUT_SERVER.write_text(text, encoding="utf-8")
    print(f"{len(entries)} ingredients written")


if __name__ == "__main__":
    main()
